CREATE TABLE IF NOT EXISTS air_quality (
    id SERIAL PRIMARY KEY,
    location TEXT,
    latitude FLOAT,
    longitude FLOAT,
    elevation FLOAT,
    utc_offset_seconds INT,
    current_time TIMESTAMPTZ,
    european_aqi FLOAT,
    us_aqi FLOAT,
    pm10 FLOAT,
    pm2_5 FLOAT,
    carbon_monoxide FLOAT,
    nitrogen_dioxide FLOAT,
    sulphur_dioxide FLOAT,
    ozone FLOAT,
    aerosol_optical_depth FLOAT,
    dust FLOAT,
    uv_index FLOAT,
    uv_index_clear_sky FLOAT,
    ammonia FLOAT,
    ragweed_pollen FLOAT,
    olive_pollen FLOAT,
    mugwort_pollen FLOAT,
    grass_pollen FLOAT,
    birch_pollen FLOAT,
    alder_pollen FLOAT
);